### ISSUE TITLE
NSIS full package included, needs to be trimmed down

### ISSUE THREAD

**Issue by GordCaswell** [PortableApps/Launcher#4]
PAL (released) currently bundles a customized copy of NSIS 2.46.5, including only the necessary plugins for PAL to work. PAL (in the repo) currently bundles the full NSIS 3.02 package. This package needs to be trimmed down to only the required plugins.

**Comment by daemondevin** [comment]
Why not just remove the need for a bundled NSIS altogether?

**Comment by JohnTHaller** [comment]
@demondevin - We used to keep NSIS separately, but it would cause issues in terms of the needed plugins for PAL and PAI as well as the needs of things we write in NSIS directly (app store/updater, backup/restore, custom launchers, etc.  We also ran into the issue of some devs only updating PAL but not NSIS or vice versa so we'd end up with it failing because they'd run it against a previous version of NSIS Portable that wouldn't have a necessary plugin.  If every dev's environment was running the PA.c Platform and updating NSIS, PAI, and PAL consistently, it wouldn't be an issue.  But that's not the case.

**Comment by 3D1T0R** [comment]
Perhaps you could make a statement that the Devs are required to use the latest versions of PAL, PAI & NSIS Portable, and any time someone hits issues, point them to it?
Or if a technological solution would be preferred, we could make PAL & PAI check the `PackageVersion` of NSIS Portable and report a warning/error if it's lower than what was the current release when they were released.
I personally think it would be better to have PAL & PAI rely on NSIS Portable instead of having three copies of NSIS, even if two of them are stripped down to the minimum requirements of PAL & PAI respectively.

**Comment by daemondevin** [comment]
This is how I deal with this issue. Note the following:
```NSIS
!ifdef StdUtils
	!ifndef ExecAsUser
		!include StdUtils.nsh
		!ifndef PLUGINSDIR
			!define PLUGINSDIR
			!AddPluginDir Plugins
		!endif
	!endif
!endif
```
The above snippet will add the plugin folder inside `../Other/Source/Plugins` which can hold all the necessary plugins needed for use within PAL.

**Comment by 3D1T0R** [comment]
@demondevin: That's an interesting idea, though I wonder about the potential for conflicts between the versions of the plugins and the version of NSIS that's trying to use them. I think it would be better simply to have it either check for the version of NSIS Portable, or have a customized error message for when a plugin isn't found that asks the user to use the latest versions of PAL, PAI and NSIS Portable.

We do on the other hand seem to be getting off-topic. I wonder if it might be best to re-purpose this issue to be for discussion about making PAL depend on NSIS Portable, as nothing is directly referencing it (yet), and move the original issue of trimming down the bundled NSIS to a new issue?

**Comment by daemondevin** [comment]
@3D1T0R You don't know much about NSIS, do you? Why the hell would there be conflicts if you tell the compiler to look in `../Other/Source/Plugins`? It's going to take the plugin in that folder regardless of what version it is. Do you understand that? 

I have never had an issue using the concept I have outlined for you guys above; **ever**.

@3D1T0R I hope the rest of your day is as pleasant as you are my friend. Good day to you sir!

**Comment by 3D1T0R** [comment]
@demondevin: I know there can be issues (perhaps "conflicts" was the wrong word?) for example when using an ANSI plugin with Unicode NSIS (and/or vice versa), and I haven't checked to see if there may be similar issues caused by NSIS 3.x trying to use a plugin written for NSIS 2.x (or vice versa), or perhaps caused by some other form of version mismatching. I'm not saying your method is wrong, or unacceptable, just that another method _may_ be better, or more acceptable, and asking if your method _may_ have a potential for causing issues down the line or not. My goodness, you don't have to be so rude.

If the possibility of issues caused by @demondevin's idea is low enough, then I'm all for it. I'd really like to have PAL & PAI rely on NSIS Portable instead of each bundling their own.

**Comment by gluxon** [comment]
Hi @demondevin.

As you've noticed, the PortableApps.com community here on GitHub is fairly new. I've mostly been lurking, but as someone who loves open source and the "social coding" this website provides, I'm incredibly excited to see one of my favorite projects developing more closely in the open.

To that extent, I want to say two things.

1. The first: Thank you for being a part of the PortableApps community here on GitHub. You have good ideas. From what I can see, you've offered potential solutions to all the issues open in this repository. I admire your volunteerism and appreciate your involvement in this new forum.

2. The second: Be a little more careful with the tone of your comments. I know it can be frustrating when someone disagrees with you, but trust me; @3D1T0R is not an idiot. He's offering feedback and I think it's valid. From my perspective, I don't think he's shutting down your idea, just pointing out the pros and cons of it. That's always a productive conversation in any technical context.

So please, can I ask you to leave out the passive aggressiveness in your future comments? Your last comment includes tone that criticizes and belittles the speaker of the argument. Critique the argument instead and avoid the personal attacks.

It's often the case that the first few members of a new community set the culture and tone of it for the future. While we're not new, we are new to working on GitHub. It would pain me if we disparaged new developers that want to help out by the perception of hostility in GitHub issue threads.

Thanks for listening. And welcome to PortableApps.com (on GitHub! 🤘)

**Comment by daemondevin** [comment]
@gluxon, While I share the same concerns as well as believe wholeheartedly to conduct oneself in a professional manner, I have already had this [same discussion][01] with @3D1T0R when he was [chastising][02] someone who was merely seeking help. When I had [pointed out][03] what he should have done, I was given a [child-like][04] temperament filled with excuses for his behavior and attacking my character instead of owning up to his mistake. 

I wasn't the only one who [felt this way][05] either. Spite his [multiple outbursts][06] at my expenses, I tried [reaching out][07] to the guy in hopes of working it out but to my surprise I was given another [outlandish retort][08], closely followed by another message soon thereafter which both had to be removed for foul content failing to abide by the *Play Nice Forum Guidelines* outlined by the moderators at PortablesApps.com. And he still refuses to [come around][09]! Even @JohnTHaller [had to say something][10] about it who then emailed me personally about the issue. @3D1T0R just [doesn't get it][11]

I'm not one to hold a grudge but @3D1T0R has brought [my lack of patience towards him upon himself][12]. So please forgive me if I greet any inept shortcomings that this man has with derision and contempt. I didn't ask for it but rest assured any respect from me towards him is null and void.

[01]: https://portableapps.com/comment/233547#comment-233547
[02]: https://portableapps.com/comment/233539#comment-233539
[03]: https://portableapps.com/comment/233545#comment-233545
[04]: https://portableapps.com/comment/233554#comment-233554
[05]: https://portableapps.com/comment/233549#comment-233549
[06]: https://portableapps.com/comment/233617#comment-233617
[07]: https://portableapps.com/comment/233657#comment-233657
[08]: https://portableapps.com/comment/233690#comment-233690
[09]: https://portableapps.com/comment/233703#comment-233703
[10]: https://portableapps.com/comment/233706#comment-233706
[11]: https://portableapps.com/comment/233707#comment-233707
[12]: https://portableapps.com/comment/233719#comment-233719

**Comment by JohnTHaller** [comment]
I think we'll keep the full set of standard plugins and includes for custom code use primarily. At least for the time being.
